name: salus
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^3.1.10
  cupertino_icons: ^1.0.2
  firebase_core: ^1.13.1
  flutter_dotenv: ^5.0.2
  flutter_mobx: ^2.0.5
  flutter_screenutil: ^5.5.1
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  mobx: ^2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1
  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.6

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/language/
    - assets/svg/
    - .env


